### ISSUE TITLE
Step 2: Jump, hop, bounce, or glide! button

### ISSUE THREAD

**Issue by megwangrpf** [raspberrypilearning/dont-fall-in#24]
The button that leads to the next step should have an extra comma after 'bounce'. If we can’t change it, no big deal. But I have changed it throughout the body text.

**Comment by libxx1** [comment]
That's great. @megwangrpf  The button comes from the meta.yml file so when you change it in there it will automatically update the next step button. As you did that, your changes will get picked up.
